// <auto-generated />
using System;
using Dresses.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dresses.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260420140651_userRoleFixed")]
    partial class userRoleFixed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dresses.Core.Entities.Business", b =>
                {
                    b.Property<int>("business_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("business_id"));

                    b.Property<string>("logoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nameBusiness")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("business_id");

                    b.ToTable("Business");
                });

            modelBuilder.Entity("Dresses.Core.Entities.Dress", b =>
                {
                    b.Property<int>("dress_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("dress_id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("businessId")
                        .HasColumnType("int");

                    b.Property<int>("cleaningDaysRequired")
                        .HasColumnType("int");

                    b.Property<decimal>("depositAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("rental_price")
                        .HasColumnType("int");

                    b.Property<int>("size")
                        .HasColumnType("int");

                    b.HasKey("dress_id");

                    b.HasIndex("businessId");

                    b.ToTable("Dresses");
                });

            modelBuilder.Entity("Dresses.Core.Entities.Rentals", b =>
                {
                    b.Property<int>("rental_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("rental_id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDepositReturned")
                        .HasColumnType("bit");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("businessId")
                        .HasColumnType("int");

                    b.Property<int>("dress_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("end_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("total_price")
                        .HasColumnType("int");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("rental_id");

                    b.HasIndex("businessId");

                    b.HasIndex("dress_id");

                    b.HasIndex("user_id");

                    b.ToTable("Rentals");
                });

            modelBuilder.Entity("Dresses.Core.Entities.Users", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("user_id"));

                    b.Property<int?>("business_id")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("role")
                        .HasColumnType("int");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("user_id");

                    b.HasIndex("business_id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Dresses.Core.Entities.Dress", b =>
                {
                    b.HasOne("Dresses.Core.Entities.Business", "business")
                        .WithMany("dresses")
                        .HasForeignKey("businessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("business");
                });

            modelBuilder.Entity("Dresses.Core.Entities.Rentals", b =>
                {
                    b.HasOne("Dresses.Core.Entities.Business", null)
                        .WithMany("rentals")
                        .HasForeignKey("businessId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Dresses.Core.Entities.Dress", "Dress")
                        .WithMany("Rentals")
                        .HasForeignKey("dress_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dresses.Core.Entities.Users", "User")
                        .WithMany("Rentals")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dress");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dresses.Core.Entities.Users", b =>
                {
                    b.HasOne("Dresses.Core.Entities.Business", null)
                        .WithMany("users")
                        .HasForeignKey("business_id");
                });

            modelBuilder.Entity("Dresses.Core.Entities.Business", b =>
                {
                    b.Navigation("dresses");

                    b.Navigation("rentals");

                    b.Navigation("users");
                });

            modelBuilder.Entity("Dresses.Core.Entities.Dress", b =>
                {
                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("Dresses.Core.Entities.Users", b =>
                {
                    b.Navigation("Rentals");
                });
#pragma warning restore 612, 618
        }
    }
}
